# MATH 210 Introduction to Mathematical Computing

## January 29, 2016

Today's Agenda:

An Introduction to NumPy:
1. Creating NumPy Arrays
2. Random Number Generator
3. Array Operations

Check out the [NumPy](http://www.numpy.org/) documentation for more information.

## An Introduction to NumPy

NumPy is the core scientific computing package in Python. Two of its main features are:

1. `ndarray`: NumPy's $n$-dimensional array object
2. Vectorized mathematical functions which broadcast across the entries of NumPy arrays for fast computation

For more documentation, see the [Official NumPy Website](http://www.numpy.org/) and the [NumPy Tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html).

When getting started with any Python package, we first need to import the package into our workspace. The standard naming convention for NumPy is the following:

In [2]:
import numpy as np

We can access the documentation for the NumPy package in the notebook using the command `np?`.

In [3]:
np?

To see what functions are available in the package, we can type `np.<TAB>` (where `<TAB>` is the tab key).

## 1. Creating NumPy Arrays

### Creating arrays from Python lists

Use the function `np.array` to create a NumPy array from a Python list of numbers:

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
type(a)

numpy.ndarray

Create a 2-dimensional array (ie. a matrix) from a list of lists:

In [6]:
M = np.array([[1,2,3],[4,5,6]])
print(M)

[[1 2 3]
 [4 5 6]]


In [7]:
type(M)

numpy.ndarray

We can make $n$-dimensional arrays from nested Python lists. For example, the following is a $3$-dimensional array:

In [8]:
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(A)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### Creating arrays using NumPy functions

There are several NumPy functions for generating arrays:

1. `np.linspace`
2. `np.arange`
3. `np.zeros`
4. `np.ones`
5. `np.eye`

The most commonly used function for generating NumPy arrays is `np.linspace` which generates an array of evenly spaced entries.

In [9]:
np.linspace?

In [10]:
a = np.linspace(0,1,11)
print(a)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


Notice that the first argument is the starting point, the second argument is the endpoint and the third argument is the length of the array (or the number of entries in the array).

In [11]:
np.linspace(0,1,101)

array([ 0.  ,  0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,
        0.09,  0.1 ,  0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,
        0.18,  0.19,  0.2 ,  0.21,  0.22,  0.23,  0.24,  0.25,  0.26,
        0.27,  0.28,  0.29,  0.3 ,  0.31,  0.32,  0.33,  0.34,  0.35,
        0.36,  0.37,  0.38,  0.39,  0.4 ,  0.41,  0.42,  0.43,  0.44,
        0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ,  0.51,  0.52,  0.53,
        0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ,  0.61,  0.62,
        0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ,  0.71,
        0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ,
        0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,
        0.9 ,  0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,
        0.99,  1.  ])

`np.arange` behaves similarly to Python's `range` function however:

1. Noninteger inputs are allowed such as `np.arange(0,2.5,0.5)`
2. The output is a NumPy array

In [12]:
np.arange?

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,2.5,0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ])

In [15]:
a1 = np.arange(0,1,0.1)
print(a1)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]


The functions `np.zeros` and `np.ones` generate arrays filled with 0's and 1's respectively. We can specify the size of the array by the argument.

In [16]:
a2 = np.zeros(7)
print(a2)

[ 0.  0.  0.  0.  0.  0.  0.]


In [17]:
a3 = np.zeros((4,3))
print(a3)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [18]:
a5 = np.ones((2,2))
print(a5)

[[ 1.  1.]
 [ 1.  1.]]


In [19]:
a4 = np.ones(5)
print(a4)

[ 1.  1.  1.  1.  1.]


The function `np.eye` generates an identity matrix and the argument is the size of the matrix.

In [20]:
Id = np.eye(4)
print(Id)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


**Exercise.** Create a $10 \times 20$ NumPy array where the $(i,j)$ entry is the Python list $[i,j]$. (Remember, the indices $i$ and $j$ start at 0.)

In [35]:
arr = np.array([ [ i+j for j in range(0,20) ] for i in range(0,10) ])
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
 [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
 [ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
 [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
 [ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]
 [ 8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28]]


**Exercise.** Create a $10 \times 10$ NumPy array where the $(i,j)$ entry is 0 if $i+j$ is even and $1$ if $i+j$ is odd. (Remember, the indices $i$ and $j$ start at 0.)

In [22]:
arr2 = np.array([ [(i + j) % 2 for i in range(0,10)] for j in range(0,10) ])
print(arr2)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


## 2. Random Number Generator

The subpackage `numpy.random` contains functions for generating random numbers from *many* different distributions. See the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.random.html) for a full list.

### Uniform Random Numbers: `numpy.random.rand`

The function `numpy.random.rand` takes a list of integers `d1,d2,...,dn` generates a NumPy array of size `(d1,...,dn)` with entries sampled from a uniform distribution over the interval $[0,1)$. If no input is given (by entering `numpy.random.rand()`), then it returns just a random number from the uniform distribution.

In [23]:
np.random.rand()

0.4055686072874831

In [24]:
np.random.rand(2)

array([ 0.20337449,  0.86462114])

In [25]:
np.random.rand(2,5)

array([[ 0.67502531,  0.59602412,  0.00825448,  0.82488547,  0.71370616],
       [ 0.47474874,  0.19688385,  0.76107768,  0.04452491,  0.49136524]])

### Normal Random Numbers: `numpy.random.randn`

The function `numpy.random.randn` works the same way and generates a NumPy array with entries sampled from a standard normal distribution.

In [26]:
# 10 random samples
for _ in range(0,10):
    print(np.random.randn())

-0.21258432848842568
0.31986726756136974
0.26463646715456957
0.21695708502201416
-0.020034853195933674
-0.3985373918420433
-0.090139520778516
-1.1154674499182635
-1.2238505005601794
0.28453479561164174


In [27]:
np.random.randn(3,4)

array([[ 0.80463414, -0.85235761,  0.3885679 , -1.16741083],
       [ 0.37996468,  0.51885754,  1.36030009,  0.63641065],
       [ 0.05615799,  1.17442303,  0.20571316,  0.51379453]])

### Random Integers: `numpy.random.randint`

The function `numpy.random.randint` takes inputs `low`, `high` and `size` and generates a NumPy array with random integers sampled uniformly from `[low,high)`. If `size` is not specified, then it returns just a random integer.

In [28]:
np.random.randint(0,6)

3

In [29]:
np.random.randint(0,2,[3,10])

array([[0, 0, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 1, 0, 0, 0, 1, 1, 1],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 0]])

In [30]:
np.random.randint(-10,10,[5,5])

array([[ -3,   2,   4,   3,  -4],
       [  9,  -8,   4, -10,  -2],
       [ -5,   0,  -6,   3,  -7],
       [  1,   6,   1,   4,  -9],
       [  8,   7,   2, -10,  -6]])

**Exercise.** Write a `while` loop which prints a random integer from $[1,7)$ until it prints a $3$ and then stops.

In [31]:
roll = np.random.randint(1,7)
while roll != 3:
    print('You rolled a ' + str(roll) + '! Try again.')
    roll = np.random.randint(1,7)
print('You rolled a ' + str(roll) + '! You win!')

You rolled a 5! Try again.
You rolled a 2! Try again.
You rolled a 2! Try again.
You rolled a 5! Try again.
You rolled a 5! Try again.
You rolled a 5! Try again.
You rolled a 5! Try again.
You rolled a 3! You win!


## 3. Array Operations

The arithmetic operations `+`, `-`, `*`, `/` and `**` are applied **elementwise** to NumPy arrays. For example, addition and subtraction of arrays behaves as you would expect by adding the arrays element by element:

In [32]:
b1 = np.array([1,2,3])
b2 = np.array([6,5,4])
print( b1 + b2 )
print( b1 - b2 )

[7 7 7]
[-5 -3 -1]


In the same way, multiplication and division of arrays is calculated element by element:

In [33]:
print( b1 * b2 )
print( b1 / b2 )

[ 6 10 12]
[ 0.16666667  0.4         0.75      ]


And exponents are applied elementwise as well:

In [34]:
print( b1 ** 2)
print( b2 ** 0.5 )
print( b1 ** b2 )

[1 4 9]
[ 2.44948974  2.23606798  2.        ]
[ 1 32 81]
