# MATH 210 Introduction to Mathematical Computing

## February 22, 2016

Today's Agenda:

1. More about functions:
    * Defining functions with parameters that have default values
    * Calling functions with positional arguments or keyword arguments
2. Approximating definite integrals with `scipy.integrate`
3. Exercises

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## 1. More about functions

Be sure to read the section on [defining functions](https://docs.python.org/3/tutorial/controlflow.html#defining-functions) in the Python tutorial.

### Defining functions with default values

Look closely at the documentation string for the `numpy` function `linspace`:

In [2]:
np.linspace?

The **variable names** in the **function definition** are called function **parameters**. But notice that there are 4 parameters with **default values**:

* `num` is the number of points in the array (default value is `50`)
* `endpoint` determines if the value `stop` is included as the last entry (default is `True`)
* `retstep` determines if the function returns a tuple of length 2 including the array and the step value instead of just the array on its own (default is `False`)
* `dtype` allows the user to specify the datatype of the entries (default is `False` which means that the function chooses what it thinks you want)

This means that when we call the function, we **must** input 2 values for the parameters `start` and `stop` but the others are optional and we can change their default values if we choose.

For example, if we don't specify `num`, then we get an array with 50 points

In [3]:
arr = np.linspace(1,50)
print(arr)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.  30.
  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.  43.  44.  45.
  46.  47.  48.  49.  50.]


Or we can pass in arguments for all the parameters:

In [4]:
arr2 = np.linspace(0,50,10,False,True,int)
print(arr2)

(array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45]), 5.0)


### Calling functions with positional arguements or keyword arguments

Notice that we called the function `np.linspace` in the previous cell above by specifying values for all the input parameters and we had to **keep track of the order in which they were entered**. This means we called the function with **positional arguments**: the first argument is the starting point, the second argument is the end point, the third argument is `num`, the fourth is `endpoint`, the fifth is `retstep`, and the sixth is `dtype`.

What if we don't want to have to remember the order? More importantly, what if we want to call the function but **only** enter values to change some default values but not all? Do we have to enter values for all the arguments?

No! We can call the function with **keyword arguments**. This just means that we call the function with the parameters names in the function call:

In [5]:
arr3 = np.linspace(1,50,dtype=int)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In fact, we can use keywords for all the arguments and the order doesn't matter!

In [6]:
arr4 = np.linspace(stop=20,dtype=int,retstep=False,start=0,num=6,endpoint=True)
print(arr4)

[ 0  4  8 12 16 20]


But usually, we call the function with a **mix of positional arguments and keyword arguments**:

In [7]:
arr5 = np.linspace(0,10,10,endpoint=False,dtype=int)
print(arr5)

[0 1 2 3 4 5 6 7 8 9]


## 2. Approximating definite integrals with `scipy.integrate`

See the notebook in `projects` folder to see an introduction to [`scipy.integrate`](http://docs.scipy.org/doc/scipy/reference/integrate.html).

## 3. Exercises

**Exercise.** Define a function called `my_int` with three parameters `y`, `x` and `method` (in that order) such that:
* `y` and `x` are arrays of the same size which represent the values of a function $y = f(x)$ over the interval $[a,b]$
* the first entry of `x` is the value $a$ and the last entry of `x` is the value $b$ (and the first and last entries of `y` are $f(a)$ and $f(b)$ respectively)
* `method` is one of the strings `trapz` or `simps` (with **default value** `trapz`)
* `my_int` returns the approximation of $\int_a^b f(x) \, dx$ using the method determined by `method`

**Exercise.** Approximate the following definite integrals using all three methods `trapz`, `simps` and `quad`:

$$\int_0^{\pi} e^{\sin x} dx$$

$$\int_{-\pi}^{\pi} \frac{\sin x}{x} dx$$

**Exercise.** (a) Write $\LaTeX \ $ code to display the definition of the Gamma function:

![gamme](https://upload.wikimedia.org/math/6/0/3/603515ff4df2cb431387e92bb6419c66.png)

(b) Define a function called `gamma_fun` with 2 parameters `t` and `b` which returns the value of the (partial) Gamma function

$$
\int_0^b x^{t-1} e^{-x} dx
$$

and such that `b` has the **default value** $10$.